;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.dw @ntsc
	.dw @pal
@ntsc:
	.dw @sfx_ntsc_0
	.dw @sfx_ntsc_1
	.dw @sfx_ntsc_2
@pal:
	.dw @sfx_pal_0
	.dw @sfx_pal_1
	.dw @sfx_pal_2

@sfx_ntsc_0:
	.db $80,$b9,$81,$fd,$82,$00,$06,$00
@sfx_pal_0:
	.db $80,$b9,$81,$eb,$82,$00,$05,$00
@sfx_ntsc_1:
	.db $80,$b9,$81,$ab,$82,$01,$12,$00
@sfx_pal_1:
	.db $80,$b9,$81,$8c,$82,$01,$0f,$00
@sfx_ntsc_2:
	.db $80,$3f,$81,$bd,$82,$00,$03,$00
@sfx_pal_2:
	.db $80,$3f,$81,$b0,$82,$00,$03,$00
